include ../tools/Makefile.base
# Customization hooks for xsltproc options
HTML_XSLTPROC_OPTS = --stringparam l10n.gentext.language de
FO_XSLTPROC_OPTS = --stringparam paper.type A4 --stringparam l10n.gentext.language de
