#!/usr/bin/python
# vim:sw=4

import sys
import os
import os.path
import shutil
import time
import string

if len(sys.argv) < 3:
    sys.stderr.write("""Usage: %s SRC-DIR TGT-DIR --dryrun

Crawl SRC-DIR looking for book translations, building distributions of
them, and exploding those distributions into TGT-DIR.
""" % (os.path.basename(sys.argv[0])))
    sys.exit(1)

BOOKSRC = sys.argv[1]
DROPSPOT = sys.argv[2]
DRYRUN = (len(sys.argv) > 3)

skip_locales = ('de',)
skip_pdf_locales = ('ru', 'zh')

# Update the working copy
if DRYRUN:
    print "SVN-Update: %s" % BOOKSRC
else:
    os.system('svn up -q ' + BOOKSRC)

# Find translations
locales = []
built_locales = []
kids = os.listdir(BOOKSRC)
for kid in kids:
    full_path = os.path.join(BOOKSRC, kid)
    if os.path.isfile(full_path):
        continue
    if os.path.exists(os.path.join(full_path, 'book')) \
       and os.path.exists(os.path.join(full_path, 'Makefile')):
        locales.append(kid)

# Build the locales
for i in skip_locales:
    try:
        locales.remove(i)
    except ValueError:
        pass
locales.sort()
cwd = os.getcwd()
for locale in locales:
    locale_dir = os.path.join(BOOKSRC, locale)
    tarball_base_name = 'svnbook-%s' % (locale)
    tarball_name = tarball_base_name + '.tar.gz'
    tarball_path = os.path.join(locale_dir, tarball_name)
    try:
        book_formats = [ 'html', 'html-chunk', 'pdf' ]
        if locale in skip_pdf_locales:
            book_formats.remove('pdf')
        command = (['../tools/book-dist.py'] + map(lambda x: '--%s' % x,
            book_formats) + ['--name="%s"' % tarball_base_name])
        os.chdir(locale_dir)
        if DRYRUN:
            print "Run: %s" % (" ".join(command))
        else:
            os.system(" ".join(command))
        os.chdir(DROPSPOT)
        if os.path.isdir(locale):
            if DRYRUN:
                print "Erase: %s/%s" % (DROPSPOT, locale)
            else:
                shutil.rmtree(locale)
        if DRYRUN:
            print "Unpack and remove: %s" % tarball_path
        else:
            os.system('tar xfz %s' % (tarball_path))
            os.rename(tarball_base_name, locale)
            os.unlink(tarball_path)
        built_locales.append(locale)
    finally:
        os.chdir(cwd)

# Write out index.html
if DRYRUN:
    print "Write index.html:"
    fp = sys.stdout
else:
    fp = open(os.path.join(DROPSPOT, 'index.html'), 'w')

fp.write("""<html>
<head>
<title>Version Control with Subversion Nightlies</title>
<style>
h1, h2, h3 { margin: 0 }
</style>
</head>
<body>
<h1><i>Version Control with Subversion</i></h1>
<h2>Automated Nightly Book Builds</h2>
<h3>Last Build Time: %s GMT</h3>
<ul>
<dl>
""" % time.asctime(time.gmtime(time.time())))
for locale in built_locales:
    fp.write("""<dt>%s</dt>
<dd>[<a href="%s/svn-book.html">single-page HTML</a>]</dd>
<dd>[<a href="%s/index.html">multi-page HTML</a>]</dd>
""" % (string.upper(locale), locale, locale))
    if locale not in skip_pdf_locales:
        fp.write('<dd>[<a href="%s/svn-book.pdf">PDF</a>]</dd>\n' % locale)
fp.write("""</dl>
</ul>
</body>
</html>
""")
