#!/usr/bin/python

import sys
import os
import os.path
import shutil
import time
import string

if len(sys.argv) < 3:
    sys.stderr.write("""Usage: %s SRC-DIR TGT-DIR

Crawl SRC-DIR looking for book translations, building distributions of
them, and exploding those distributions into TGT-DIR.
""" % (os.path.basename(sys.argv[0])))
    sys.exit(1)

BOOKSRC = sys.argv[1]
DROPSPOT = sys.argv[2]

# Update the working copy
os.system('svn up -q ' + BOOKSRC)

# Find translations
locales = []
built_locales = []
kids = os.listdir(BOOKSRC)
for kid in kids:
    full_path = os.path.join(BOOKSRC, kid)
    if os.path.isfile(full_path):
        continue
    if os.path.exists(os.path.join(full_path, 'book')) \
       and os.path.exists(os.path.join(full_path, 'Makefile')):
        locales.append(kid)

# Build the locales
locales.sort()
cwd = os.getcwd()
for locale in locales:
    locale_dir = os.path.join(BOOKSRC, locale)
    tarball_base_name = 'svnbook-%s' % (locale)
    tarball_name = tarball_base_name + '.tar.gz'
    tarball_path = os.path.join(locale_dir, tarball_name)
    try:
        os.chdir(locale_dir)
        os.system('../tools/book-dist.py --html --html-chunk --pdf ' + \
                  '--name="%s"' % (tarball_base_name))
        os.chdir(DROPSPOT)
        if os.path.isdir(locale):
            shutil.rmtree(locale)
        os.system('tar xfz %s' % (tarball_path))
        os.rename(tarball_base_name, locale)
        os.unlink(tarball_path)
        built_locales.append(locale)
    except:
        pass

# Write out index.html
fp = open(os.path.join(DROPSPOT, 'index.html'), 'w')
fp.write("""<html>
<head>
<title>Version Control with Subversion Nightlies</title>
<style>
h1, h2, h3 { margin: 0 }
</style>
</head>
<body>
<h1><i>Version Control with Subversion</i></h1>
<h2>Automated Nightly Book Builds</h2>
<h3>Last Build Time: %s GMT</h3>
<ul>
<dl>
""" % time.asctime(time.gmtime(time.time())))
for locale in built_locales:
    fp.write("""<dt>%s</dt>
<dd>[<a href="%s/svn-book.html">single-page HTML</a>]</dd>
<dd>[<a href="%s/index.html">multi-page HTML</a>]</dd>
<dd>[<a href="%s/svn-book.pdf">PDF</a>]</dd>
""" % (string.upper(locale), locale, locale, locale))
fp.write("""</dl>
</ul>
</body>
</html>
""")
